id: I5C4985EF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T09:20:15+00:00'
last_modified: '2022-06-08T16:14:58.033433+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21837
  title: མར་པ་ལོ་ཙཱའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E109:
      image_group_id: I1KG21943
      title: ''
      total_pages: 206
      order: 1
      base_file: E109.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
