id: P010613
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:16:31.925193
source_metadata:
  id: bdr:W1KG21837
  title: མར་པ་ལོ་ཙཱའི་རྣམ་ཐར།
  author: ''
  volumes:
    ff970553994c4aad86b7fee483f365da:
      image_group_id: I1KG21943
      title: ''
      volume_number: 1
      total_pages: 206
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
